/**
 * FE-BETA-02 — contract alignment helpers, exercised against the REAL
 * /genetics/analyze-upload responses of the eight smoke-kit v1.1 files
 * (src/test/fixtures/smokeKit, generated by backend 9544b562).
 */
import { describe, expect, it } from "vitest";
import {
  anovaSourceLabelMap,
  canOpenHistoryRow,
  cooksReviewFlag,
  countPublicationReady,
  dedupeHistoryByRunId,
  defaultDesignForBlockMapping,
  describeCooksReview,
  describeResponseExclusion,
  describeTraitFailure,
  emphasiseAnovaRow,
  messageFromErrorBody,
  orderByLevelOrder,
  readBackendCvPercent,
  readCooksReview,
  readLevelOrder,
  resolveAnovaSourceLabels,
  resolveReleaseStatus,
  rewriteMappingWarning,
} from "../feBeta02";

import crd01 from "@/test/fixtures/smokeKit/VS_Smoke_01_CRD.json";
import factCrd02 from "@/test/fixtures/smokeKit/VS_Smoke_02_Factorial_CRD.json";
import rcbd03 from "@/test/fixtures/smokeKit/VS_Smoke_03_RCBD.json";
import factRcbd04 from "@/test/fixtures/smokeKit/VS_Smoke_04_Factorial_RCBD.json";
import split05 from "@/test/fixtures/smokeKit/VS_Smoke_05_SplitPlot_RCBD.json";
import refusal06 from "@/test/fixtures/smokeKit/VS_Smoke_06_RCBD_missing_plot.json";
import refusal07 from "@/test/fixtures/smokeKit/VS_Smoke_07_RCBD_text_in_response.json";
import crd08 from "@/test/fixtures/smokeKit/VS_Smoke_08_CRD_blank_cell.json";

type Payload = Record<string, any>;
const firstTrait = (p: Payload) => Object.values(p.trait_results as Record<string, any>)[0];
const resultOf = (p: Payload) => firstTrait(p).analysis_result.result;

describe("1. defaultDesignForBlockMapping — Block = None resolves to CRD", () => {
  it("is CRD when there is no block column", () => {
    expect(defaultDesignForBlockMapping("")).toBe("crd");
    expect(defaultDesignForBlockMapping("   ")).toBe("crd");
    expect(defaultDesignForBlockMapping(null)).toBe("crd");
    expect(defaultDesignForBlockMapping(undefined)).toBe("crd");
  });
  it("is RCBD when a block column is mapped", () => {
    expect(defaultDesignForBlockMapping("rep")).toBe("rcbd");
  });
});

describe("2. ANOVA source labels follow anova_table.display_source", () => {
  it("uses the backend display label, not the internal 'genotype' key (real CRD payload)", () => {
    const table = resultOf(crd01).anova_table;
    expect(table.source).toEqual(["genotype", "Residuals"]);
    expect(table.display_source).toEqual(["treatment", "Residuals"]);
    expect(resolveAnovaSourceLabels(table)).toEqual(["treatment", "Residuals"]);
    expect(anovaSourceLabelMap(table).get("genotype")).toBe("treatment");
  });

  it("uses the backend labels for the split-plot error strata (real payload)", () => {
    const table = resultOf(split05).anova_table;
    expect(resolveAnovaSourceLabels(table)).toEqual([
      "Replication", "irrigation", "Error A", "variety", "irrigation×variety", "Error B",
    ]);
  });

  it("falls back to neutral labels ONLY when display_source is absent (legacy payload)", () => {
    const legacy = { source: ["rep", "genotype", "Residuals"] };
    expect(resolveAnovaSourceLabels(legacy)).toEqual(["Replication / Block", "Treatment", "Residuals"]);
  });

  it("falls back per row when the backend left a label blank", () => {
    const partial = { source: ["rep", "genotype"], display_source: ["Block", ""] };
    expect(resolveAnovaSourceLabels(partial)).toEqual(["Block", "Treatment"]);
  });
});

describe("3. significance emphasis — replication/block is never a treatment finding", () => {
  it("emphasises a treatment row at or below alpha", () => {
    expect(emphasiseAnovaRow("genotype", 0.0016, 0.05)).toBe(true);
    expect(emphasiseAnovaRow("irrigation", 0.0068, 0.01)).toBe(true);
  });
  it("does not emphasise a significant replication / block row", () => {
    expect(emphasiseAnovaRow("rep", 0.001, 0.05)).toBe(false);
    expect(emphasiseAnovaRow("Replication", 0.0001, 0.05)).toBe(false);
    expect(emphasiseAnovaRow("block", 0.02, 0.05)).toBe(false);
  });
  it("does not emphasise error rows, missing p-values or p above alpha", () => {
    expect(emphasiseAnovaRow("Residuals", 0.001, 0.05)).toBe(false);
    expect(emphasiseAnovaRow("Error A", 0.001, 0.05)).toBe(false);
    expect(emphasiseAnovaRow("genotype", null, 0.05)).toBe(false);
    expect(emphasiseAnovaRow("genotype", 0.2, 0.05)).toBe(false);
  });
});

describe("4. CV% is shown only when the backend supplies it — never computed", () => {
  it("the validated one-factor payloads carry no CV, so none is produced", () => {
    // Documented contract gap (see FE-BETA-02 report): descriptive_stats is null.
    for (const p of [crd01, rcbd03, crd08] as Payload[]) {
      expect(resultOf(p).descriptive_stats).toBeNull();
      expect(readBackendCvPercent(resultOf(p))).toBeNull();
    }
  });
  it("reads descriptive_stats.cv_percent verbatim when a backend supplies it", () => {
    expect(readBackendCvPercent({ descriptive_stats: { cv_percent: 3.1957908949 } })).toBe(3.1957908949);
  });
  it("ignores non-finite or negative values and never derives one from the ANOVA table", () => {
    expect(readBackendCvPercent({ descriptive_stats: { cv_percent: Number.NaN } })).toBeNull();
    expect(readBackendCvPercent({ descriptive_stats: { cv_percent: -1 } })).toBeNull();
    expect(readBackendCvPercent({ anova_table: resultOf(rcbd03).anova_table, grand_mean: 14.818 })).toBeNull();
  });
});

describe("5. level_order", () => {
  it("Factorial RCBD smoke example orders nitrogen as N0, N60, N120 (real payload)", () => {
    const order = readLevelOrder(resultOf(factRcbd04));
    expect(order.factor_a).toEqual(["N0", "N60", "N120"]);
    expect(order.factor_b).toEqual(["V1", "V2"]);
    expect(order.block).toEqual(["B1", "B2", "B3"]);
    // Lexical order would put N120 first — exactly what level_order prevents.
    expect([...(order.factor_a ?? [])].sort()).toEqual(["N0", "N120", "N60"]);
  });

  it("orders an unranked list by level_order and keeps unknown keys last, stably", () => {
    const items = [{ k: "N120" }, { k: "N0" }, { k: "X" }, { k: "N60" }];
    const out = orderByLevelOrder(items, (i) => i.k, ["N0", "N60", "N120"]).map((i) => i.k);
    expect(out).toEqual(["N0", "N60", "N120", "X"]);
  });

  it("returns the input untouched when no order is supplied", () => {
    const items = [{ k: "b" }, { k: "a" }];
    expect(orderByLevelOrder(items, (i) => i.k, undefined)).toBe(items);
  });

  it("the ranked mean-separation table is NOT reordered by level_order", () => {
    // The backend ranks marginal means (N120 highest first); that ranking is the
    // statistical presentation and must be left alone.
    expect(resultOf(factRcbd04).mean_separation.genotype).toEqual(["N120", "N60", "N0"]);
  });

  it("covers every design family in the kit", () => {
    expect(readLevelOrder(resultOf(crd01)).treatment).toEqual(["1", "2", "3", "4"]);
    expect(readLevelOrder(resultOf(rcbd03)).treatment).toHaveLength(5);
    expect(readLevelOrder(resultOf(factCrd02)).factor_a).toEqual(["P0", "P1"]);
    expect(readLevelOrder(resultOf(split05)).main_plot).toEqual(["Rainfed", "Irrigated"]);
    expect(readLevelOrder(resultOf(split05)).sub_plot).toEqual(["V1", "V2", "V3"]);
  });
});

describe("6. structured errors never show raw JSON", () => {
  it("uses detail.message for a structured 4xx", () => {
    expect(
      messageFromErrorBody({ detail: { code: "x", message: "Column 'yield' has text in row 14." } }, 400),
    ).toBe("Column 'yield' has text in row 14.");
  });
  it("keeps a plain string detail", () => {
    expect(messageFromErrorBody({ detail: "Analysis failed upstream" }, 500)).toBe("Analysis failed upstream");
  });
  it("summarises a 422 validation array into readable lines", () => {
    const text = messageFromErrorBody(
      { detail: [{ loc: ["body", "trait_columns"], msg: "field required", type: "value_error.missing" }] },
      422,
    );
    expect(text).toBe("trait_columns: field required");
    expect(text).not.toContain("{");
    const multi = messageFromErrorBody(
      { detail: [
        { loc: ["body", "alpha"], msg: "unexpected value" },
        { loc: ["body", "mode"], msg: "field required" },
      ] },
      422,
    );
    expect(multi).toContain("alpha: unexpected value");
    expect(multi).toContain("mode: field required");
  });
  it("never echoes a JSON string and falls back to a plain sentence", () => {
    expect(messageFromErrorBody('{"detail":{"message":"Nope"}}')).toBe("Nope");
    const generic = messageFromErrorBody({ unexpected: { shape: true } });
    expect(generic).not.toMatch(/[{}[\]]/);
  });

  it("real-kit refusal VS_Smoke_06 — missing structural cell keeps the offending cell", () => {
    const failure = describeTraitFailure(firstTrait(refusal06));
    expect(failure.code).toBe("rcbd_missing_cells");
    expect(failure.heading).toBe("The design is incomplete");
    expect(failure.message).toContain("TOC-03");
    expect(failure.message).toContain("R2");
    expect(failure.message).toBe(firstTrait(refusal06).structural_validation.message);
  });

  it("real-kit refusal VS_Smoke_07 — text 'dead' keeps value, treatment and block, and is not a 'design' error", () => {
    const failure = describeTraitFailure(firstTrait(refusal07));
    expect(failure.code).toBe("rcbd_non_numeric_response");
    expect(failure.heading).toBe("A response value is not a number");
    expect(failure.message).toContain("'dead'");
    expect(failure.message).toContain("TOC-03");
    expect(failure.message).toContain("R3");
    expect(failure.message).toMatch(/correct or clear these cells/);
  });

  it("prefers structural_validation.message over the trait error string", () => {
    const f = describeTraitFailure({ error: "generic", structural_validation: { code: "x", message: "specific" } });
    expect(f.message).toBe("specific");
    expect(describeTraitFailure({ error: "only error" }).message).toBe("only error");
  });
});

describe("7. release status drives maturity, reopenability and disclosure", () => {
  const status = (p: Payload) => resolveReleaseStatus(p.release_status, undefined);

  it("RCBD: Early Access, durable saved-run reopening available (real payload)", () => {
    const s = status(rcbd03 as Payload);
    expect(s.maturity).toBe("early_access");
    expect(s.reopenable).toBe(true);
    expect(s.persistence).toBe("durable_saved_run");
    expect(s.label).toBe("Early Access · saved runs can be reopened");
    expect(s.disclosure).toMatch(/RCBD runs saved/);
    expect(s.source).toBe("backend");
  });

  it("CRD: Early Access, Word download, NOT reopenable (real payloads 01 and 08)", () => {
    for (const p of [crd01, crd08] as Payload[]) {
      const s = status(p);
      expect(s.maturity).toBe("early_access");
      expect(s.reopenable).toBe(false);
      expect(s.persistence).toBe("report_download_only");
      expect(s.label).toBe("Early Access · Word report download");
      expect(s.label).not.toMatch(/reopen/i);
      expect(s.disclosure).toMatch(/Saved-run reopening is currently available for RCBD only/);
    }
  });

  it("Factorial CRD / RCBD and Split-Plot: Preview, session-only (real payloads 02, 04, 05)", () => {
    for (const p of [factCrd02, factRcbd04, split05] as Payload[]) {
      const s = status(p);
      expect(s.maturity).toBe("preview");
      expect(s.reopenable).toBe(false);
      expect(s.persistence).toBe("session_only");
      expect(s.label).toBe("Preview · session-only");
      expect(s.disclosure).toMatch(/session-only/);
    }
  });

  it("a Preview status can never claim reopenable, even if a payload said so", () => {
    expect(resolveReleaseStatus({ maturity: "preview", reopenable: true, persistence: "session_only" }).reopenable).toBe(false);
  });

  it("falls back to the design for payloads / history rows without release_status", () => {
    expect(resolveReleaseStatus(null, "rcbd")).toMatchObject({ maturity: "early_access", reopenable: true, source: "design_fallback" });
    expect(resolveReleaseStatus(undefined, "crd")).toMatchObject({ maturity: "early_access", reopenable: false });
    for (const d of ["factorial_crd", "factorial_rcbd", "split_plot_rcbd", "factorial"]) {
      expect(resolveReleaseStatus(undefined, d)).toMatchObject({ maturity: "preview", reopenable: false });
    }
    expect(resolveReleaseStatus(undefined, "genetic_parameters")).toMatchObject({ maturity: "unknown", label: "" });
  });
});

describe("7b/8. history: Open action, publication-ready count, run-id de-duplication", () => {
  const row = (design: string | null, extra: Record<string, unknown> = {}, status = "success") => ({
    analysis_status: status,
    design_type: design,
    analysis_parameters: extra,
  });

  it("offers Open only where reopenable; Preview and CRD rows get none", () => {
    expect(canOpenHistoryRow(row("rcbd"))).toBe(true);
    expect(canOpenHistoryRow(row("crd"))).toBe(false);
    expect(canOpenHistoryRow(row("factorial_crd"))).toBe(false);
    expect(canOpenHistoryRow(row("factorial_rcbd"))).toBe(false);
    expect(canOpenHistoryRow(row("split_plot_rcbd"))).toBe(false);
    // Non-ANOVA modules keep their existing module-level Open.
    expect(canOpenHistoryRow(row(null))).toBe(true);
  });

  it("prefers the recorded release_status over the design", () => {
    const recorded = row("rcbd", { release_status: { maturity: "preview", reopenable: false, persistence: "session_only" } });
    expect(canOpenHistoryRow(recorded)).toBe(false);
  });

  it("Preview analyses do not count toward publication-ready", () => {
    const rows = [
      row("rcbd"), row("crd"), row(null),
      row("factorial_crd"), row("factorial_rcbd"), row("split_plot_rcbd"),
      row("rcbd", {}, "failure"),
    ];
    expect(countPublicationReady(rows)).toEqual({ publicationReady: 3, preview: 3, notSuccessful: 1 });
  });

  it("de-duplicates RECOVERED_COMPLETE by analysis_run_id and keeps rows without one", () => {
    const a = { id: "1", analysis_parameters: { persistence_analysis_run_id: "run-A", persistence_outcome: "COMPLETE" } };
    const aRecovered = { id: "2", analysis_parameters: { persistence_analysis_run_id: "run-A", persistence_outcome: "RECOVERED_COMPLETE" } };
    const b = { id: "3", analysis_parameters: { persistence_analysis_run_id: "run-B" } };
    const noId1 = { id: "4", analysis_parameters: {} };
    const noId2 = { id: "5", analysis_parameters: {} };
    expect(dedupeHistoryByRunId([a, aRecovered, b, noId1, noId2]).map((r) => r.id)).toEqual(["1", "3", "4", "5"]);
  });
});

describe("10. response_exclusion disclosure (CRD blank response)", () => {
  it("describes original N, analysed N, excluded row, per-treatment n and unequal replication (real VS_Smoke_08)", () => {
    const view = describeResponseExclusion(resultOf(crd08).response_exclusion)!;
    const byLabel = Object.fromEntries(view.lines.map((l) => [l.label, l.value]));
    expect(byLabel["Original N"]).toBe("16");
    expect(byLabel["Analysed N"]).toBe("15");
    expect(byLabel["Excluded"]).toBe("row 10 (treatment 3, blank)");
    expect(byLabel["Observations per treatment"]).toBe("1 = 4, 2 = 4, 3 = 3, 4 = 4");
    expect(view.unequalReplicationNote).toMatch(/unequal/);
  });
  it("never calls an excluded blank cell an outlier", () => {
    const view = describeResponseExclusion(resultOf(crd08).response_exclusion)!;
    const text = JSON.stringify(view).toLowerCase();
    expect(text).not.toContain("outlier");
  });
  it("is absent for designs that refuse incomplete data", () => {
    for (const p of [crd01, rcbd03, factCrd02, factRcbd04, split05] as Payload[]) {
      expect(describeResponseExclusion(resultOf(p).response_exclusion)).toBeNull();
    }
  });
  it("omits the unequal-replication note when the backend does not report it", () => {
    const view = describeResponseExclusion({ original_n: 12, effective_n: 11, unequal_replication: false })!;
    expect(view.unequalReplicationNote).toBeNull();
  });
});

describe("11. Cook's distance contract — new fields first, legacy fallback", () => {
  it("reads the new fields from a real payload that carries both (VS_Smoke_01 CRD)", () => {
    const review = readCooksReview(resultOf(crd01).outlier_summary);
    expect(review.reviewFlagCount).toBe(2);
    expect(review.threshold).toBe(0.25);
    expect(review.rule).toBe("D > 4/n");
  });
  it("reads the new fields from RCBD / factorial / split-plot payloads (no legacy alias)", () => {
    expect(readCooksReview(resultOf(rcbd03).outlier_summary)).toMatchObject({ reviewFlagCount: 3, threshold: 0.2 });
    expect(readCooksReview(resultOf(factRcbd04).outlier_summary).reviewFlagCount).toBe(3);
    expect(readCooksReview(resultOf(split05).outlier_summary).reviewFlagCount).toBe(4);
  });
  it("prefers the new name when the two disagree", () => {
    expect(readCooksReview({ n_cooks_distance_review_flags: 1, n_influential_observations: 9 }).reviewFlagCount).toBe(1);
  });
  it("falls back to the legacy names for older payloads", () => {
    const review = readCooksReview({ n_influential_observations: 2, cooks_threshold: 0.3 });
    expect(review).toMatchObject({ reviewFlagCount: 2, threshold: 0.3 });
    expect(cooksReviewFlag({ influential: true })).toBe(true);
    expect(cooksReviewFlag({ cooks_distance_review_flag: false, influential: true })).toBe(false);
  });
  it("never labels the 4/n screen as proof of influence", () => {
    const text = describeCooksReview(readCooksReview(resultOf(crd01).outlier_summary))!;
    expect(text).toMatch(/screening/i);
    expect(text).toMatch(/not proof/i);
    // Worded as a review prompt: the only mention of "influential" is the disclaimer.
    expect(text).not.toMatch(/(?<!not proof that an observation )\b(is|are) influential\b/i);
    expect(text).toContain("(0.250)");
    expect(describeCooksReview({ reviewFlagCount: null, threshold: null, rule: null })).toBeNull();
  });
});

describe("9. mapping warning wording", () => {
  const backend =
    "If your column contains numeric treatment levels (e.g. 0, 50, 100 kg N/ha or storage days 1, 3, 6, 9), toggle it to Treatment Factor.";
  it("replaces the 'toggle' instruction with a control that exists", () => {
    const text = rewriteMappingWarning(backend);
    expect(text).not.toMatch(/toggle/i);
    expect(text).toContain("Treatment / Factor Column");
  });
  it("leaves other warnings untouched", () => {
    expect(rewriteMappingWarning("Column 'x' has 3 missing values.")).toBe("Column 'x' has 3 missing values.");
  });
});
